services:
  triton:
    image: rcland12/detection-stream:linux-triton-latest
    container_name: triton
    build:
      context: ./triton
    network_mode: host
    shm_size: 512mb
    volumes:
      - ./triton:/models
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: [ "CMD", "curl", "-i", "-X", "GET", "http://localhost:8000/v2/health/ready" ]
      interval: 5s
      timeout: 10s
      retries: 6

  app:
    image: rcland12/detection-stream:linux-latest
    container_name: app
    build:
      context: ./app
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/argus_socket:/tmp/argus_socket
      - ./triton:/root/app/triton
    env_file: .env


  nginx-stream:
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./nginx
    network_mode: host
    volumes:
      - ./nginx/nginx-stream/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx-web:
    image: rcland12/detection-stream:nginx-latest
    build:
      context: ./nginx
    network_mode: host
    volumes:
      - ./nginx/nginx-web/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/stream:/var/www/html/stream
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
