name: "postprocess"
backend: "python"
max_batch_size: 0

input [
  {
    name: "detections"
    data_type: TYPE_FP16
    dims: [ 1, 84, 8400 ]
  }
]

output [
  {
    name: "bounding_boxes"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]

parameters [{
  key: "CUDA_VISIBLE_DEVICES"
  value: { string_value: "0" }
}]

optimization {
  execution_accelerators {
    gpu_execution_accelerator : [{
      name : "tensorrt"
      parameters: { key: "precision_mode" value: "FP16" }
      parameters: { key: "max_workspace_size_bytes" value: "1073741824" }
    }]
  }
}

version_policy: { 
  latest: { num_versions: 1 }
}
